### ISSUE TITLE
Create package DOI

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#100]
Instructions: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Tuning: https://github.com/castelao/inception

**Comment by jessecusack** [comment]
@gunnarvoet, is this the journal you were thinking about? https://joss.theoj.org/about. It seems quite straightforward.

I'm not sure if we should do a paper or just a zenodo DOI. (Maybe we could have both?) The paper seems more authoritative since it will be peer reviewed and explain a bit about the package.

**Comment by gunnarvoet** [comment]
Yes, that's the one that I talked about. However, I also still agree with your notion that it would be much nicer to have an actual research paper that applies at least one of the mixsea methods.

**Comment by opinner** [comment]
For the paper I am currently writing, I use the Thorpe's Scale and Shear-strain parametrization from mixsea. @gunnarvoet will be on it as a co-author. How would you like me to reference this code? Do you want to create a Zenodo-DOI? That also wouldn't prevent a future paper of yourselves.

**Comment by gunnarvoet** [comment]
Hi @opinner - thanks for bringing this up! I will look into getting a zenodo doi for the package.

**Comment by gunnarvoet** [comment]
@opinner I set up a doi:
v0.1.2: https://www.doi.org/10.5281/zenodo.10636077
overall doi: https://www.doi.org/10.5281/zenodo.10636076
