### ISSUE TITLE
Frequency shift bug

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/mixsea#104]
@amyfw pointed out that shifting frequencies from neg/pos to positive only does not work as it is supposed to be, leading to errors in the output from the `psd` function.

Replacing these lines
https://github.com/modscripps/mixsea/blob/e114999eb363cd5fafb4a08dc1983f84ba865e4f/mixsea/helpers.py#L169-L175
with
```python
f0 = np.fft.fftshift(f0) + abs(f0).max()
```
should fix the bug.

It would be good to add some tests for the `psd` function (as I think was also suggested in #83).

**Comment by jklymak** [comment]
Is there a reason to roll your own psd versus using the scipy version?

**Comment by gunnarvoet** [comment]
Only historical reasons as this started out from translating a set of Matlab functions into Python...
