### ISSUE TITLE
Broken DOI for Kunze2006 in references

### ISSUE THREAD

**Issue by opinner** [modscripps/mixsea#116]
![grafik](https://github.com/modscripps/mixsea/assets/32843689/409f01c0-ea81-48b7-b9f1-15bcaf6197c0)

In the references section of the documentation, this doi link is broken. From my point of view, there is either a _doi.org_ too much or a _https://_ too few. It can probably be adjusted quickly in docs/references.bib.

It is an error will absolutely negligible consequences, but I stumbled on it by accident.

**Comment by gunnarvoet** [comment]
Thanks @opinner !
