### ISSUE TITLE
intermediate profile method should be optional

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#13]
By my reading of the code this method is applied automatically, but there should probably be a boolean argument in the overturns function that switches it on/off. It should probably also be split into a separate function.

**Comment by gunnarvoet** [comment]
Agreed, this should be optional and outside the main function. I would
envision that you can turn both this and/or Galbraith/Kelley on or off.

**Comment by gunnarvoet** [comment]
This looks great! I love the detailed discussion of the different methods, including different attempts to calculate N^2.

**Comment by jessecusack** [comment]
Great thank you! It was actually very helpful for my own understanding to produce that comparison. I think the reason the teos method gets higher N2 is because it uses points just outside the overturning patches. Eyeball inspection tells me that overturning patches (when sorted) are typically weakly stratified while the region either side is often strongly stratified. Perhaps, it should use the first and last point within the overturn? If I remember right, Glenn was testing out these methods on his microstructure data. It might be good to include that as an example somewhere...

Also, my detailed look at the intermediate profile method worries me. It creates havoc with sorted indices - since - how does the sorting function deal with a bunch of data points that have an identical value? As a result, the Thorpe displacements just look weird. Maybe in the grand scheme of things this doesn't matter and the answer comes out about the same, but it leaves me with a bad feeling about the method!
