### ISSUE TITLE
notebooks for documentation 

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#15]
The nbsphinx extension seems like a convenient way to include notebooks as part of the documentation. I think it is worth a try to implement.

**Comment by gunnarvoet** [comment]
Looks pretty straight forward and I agree that writing a notebook is easier than trying to get all the code cells right in rst format. Plus, the user can grab the notebook and start adjusting it.

**Comment by gunnarvoet** [comment]
I'll give this a shot - will simply convert the current tutorial (thanks for including the overturn example!) into a notebook.
