### ISSUE TITLE
Should Thorpe scale Lt be a default output?

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#25]
Currently it is in diagnostics but perhaps it should be a standard output? I'm not sure...

**Comment by gunnarvoet** [comment]
I did like your approach of only having a minimal default output and then the rest in the diagnostics. I would opt for having Lt in the diagnostics but am also happy to be convinced otherwise.

**Comment by jessecusack** [comment]
Ok so we both lean towards leaving it as a diagnostic. I'll close this.
