### ISSUE TITLE
Unify input variable names

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/mixsea#33]
Input variable names for salinity, temperature etc. should be consistent across the module. Currently some functions have them capitalized, others don't. I'm happy with either.

Also, it would be nice to have the basic input parameters in the same order.

**Comment by jessecusack** [comment]
Perhaps we should follow the gsw package and use:
SP: practical salinity
t: in situ temperature
p: pressure
CT: conservative temperature
SA: absolute salinity
z: height (-depth)

Although I find 'SP' a bit awkward and personally prefer just 's' or 'S' it is not the hill I would choose to die on.

**Comment by gunnarvoet** [comment]
Following gsw may be a good solution. At the moment I would object to moving z from depth to height though. I did this recently in a different context and it turned out to be a big mess...

**Comment by jessecusack** [comment]
Yes I can see how global search and replace doesn't work well with 'z'. Nevertheless, I am firmly in the z = height and depth = -z camp when it comes to naming variables ;)

I wouldn't go so far as to suggest we make all functions require height instead of depth, just that depth be called depth...

**Comment by gunnarvoet** [comment]
Agreed.

**Comment by gunnarvoet** [comment]
Preferred order of variables
depth, t, s, lon, lat

**Comment by jessecusack** [comment]
And following gsw would that be, depth, t, SP, lon, lat?
