### ISSUE TITLE
why p and z as arguments in shearstrain?

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#38]
I notice that both p and z are required arguments, why not use `gsw.z_from_p` or `gsw.p_from_z`?

**Comment by gunnarvoet** [comment]
I think I was just lazy when putting this together. I will change this to use only one of them.

**Comment by jessecusack** [comment]
I guess strictly speaking the data should be in depth or height for the most accurate  vertical wavenumber spectra, since p -> z conversion is not exactly proportional and would result in depths that are not perfectly evenly spaced. However, I would be surprised if this makes any significant difference to the final result.

**Comment by gunnarvoet** [comment]
Closed by #51 .
