### ISSUE TITLE
decide on default values

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#43]
One that jumps to mind is to set intermediate profile method False by default in overturns.

**Comment by gunnarvoet** [comment]
The `shearstrain` currently has a number of default values to be able to run it out of the box:

- N^2 smoothing technique
- Wavenumber integration ranges for shear and strain
- Depth window size
- Depth window overlap (currently hardwired, see #30)

One could probably argue about each of these. I think that (at some point) including parameter choices for specific studies should be the best way forward.

In general, good documentation of the available parameter choices and their impact may be more important than the default values themselves.

**Comment by jessecusack** [comment]
I agree. I'll think about what I can add to the documentation.

**Comment by gunnarvoet** [comment]
I think the documentation is well underway towards explaining the consequences of parameter choices, especially for the Thorpe scale method.

Let' close this. I will open an issue for improving the shearstrain documentation in terms of explaining parameters, I think there is still room for improvement. I don't think it is critical for the v0.1.0 release though.
