### ISSUE TITLE
alpha or alphasq?

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#44]
In `eps_overturn` I have stuck with the original code and used alpha^2. However, it seems more natural to me to specify alpha since the scales are directly related as Lozmidiv = alpha*Lthorpe. Opinions?

**Comment by gunnarvoet** [comment]
I would vote for alpha instead of alpha^2.

**Comment by jessecusack** [comment]
Closed by https://github.com/modscripps/mixsea/pull/45
