### ISSUE TITLE
Merge intermediate_profile_example.ipynb into thorpe_scales.ipynb

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/mixsea#54]
I removed `intermediate_profile_example.ipynb` from `index.rst` in #53 as the intermediate profile method is also covered in `thorpe_scales.ipynb`. There may still be some bits and pieces that we want to keep though, so I haven't deleted the file yet. @jessecusack maybe you can have a quick look at it.

**Comment by jessecusack** [comment]
It should be easy to merge them.
