### ISSUE TITLE
Remove 'cannot install via pip' note from quick start

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#64]
It can now!

**Comment by jessecusack** [comment]
Ah, I just realised that readthedocs builds the 'stable'  release. Can we somehow incorporate this?

**Comment by gunnarvoet** [comment]
We could have readthedocs point to master by default for now and do a little bug fix release soon?

**Comment by gunnarvoet** [comment]
I went ahead and set readthedocs to point to master by default.

**Comment by jessecusack** [comment]
I think this is a reasonable solution for now. I'll make a quick issue to remind us.
