### ISSUE TITLE
Shear strain documentation bug?

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#67]
In the section 'missing data' of the shear strain documentation, the text states that `nan_shearstrain` should produce the same results as `shearstrain`, however the figure suggests they do not? 

I haven't dug in to figure out why yet.

**Comment by gunnarvoet** [comment]
I think maybe the figure is just misleading - left panel shows shear/strain, right panel strain only. The curves actually do the show results, it is just hard to see. I'll change this to make it clearer.

**Comment by jessecusack** [comment]
I see, the comparison is between epsilon from the `nan` function vs from the normal function. Whereas the figure above compares two different N2 methods.

Perhaps change the legend in the missing data figure to specify NaN and normal rather than the polynomial fit. Could set the title to distinguish between strain only and shear+strain?

**Comment by gunnarvoet** [comment]
Yes, these are good recommendations. Overall this section is a little awkward but I'll fix it like this for now.
