### ISSUE TITLE
Option for using temperature in overturns

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/mixsea#7]
Right now it is only density, make it optional to use temperature instead.

**Comment by jessecusack** [comment]
I think the first step in achieving this would be to create a function that searches for overturns for the most basic possible input z (depth/height) and quantity q (temp/dens/whatever) with probably some accuracy parameter dq.

**Comment by gunnarvoet** [comment]
Agreed!

**Comment by jessecusack** [comment]
Closed by https://github.com/modscripps/mixsea/pull/36
