### ISSUE TITLE
Calculating overturns from density alone

### ISSUE THREAD

**Issue by hdrake** [modscripps/mixsea#75]
Since the overturn Thorpe scale method only requires density and pressure (or depth) as inputs, it seems unnecessarily restrictive that the main function `mixsea.overturn.eps_overturn` requires temperature and salinity.

For example, I was trying to write up a simple unit test that confirms the sorting method recovers the analytical solution from Thorpe '77, but this is extremely difficult in the current code because one has to find a temperature and salinity profile consistent with the prescribed density (and deal with non-linearities of the EOS).

**Comment by hdrake** [comment]
Thorpe's example:

<img width="387" alt="Screen Shot 2021-10-10 at 7 53 35 PM" src="https://user-images.githubusercontent.com/12971166/136711182-c8a63af9-f5ed-4481-93ac-5afb46d137e4.png">

```python
import mixsea as mx
import gsw
import numpy as np
import matplotlib.pyplot as plt

dz = 1.
z0 = 2200.
H = 100.
h = 50.
z = np.arange(z0-H, z0+H, dz)
p=gsw.p_from_z(-z, 0.)

ρ0 = 1041.4
T0 = 4.
S0 = 35.

Δ = -1e-4

ρ = np.zeros_like(z)
ρ[(H >= z-z0) & (z-z0 >= h)] = ρ0*(1-Δ)
ρ[np.abs(z-z0) < h] = ρ0*(1+Δ*np.sin(3*np.pi*(z-z0)[np.abs(z-z0) < h]/(2*h)))
ρ[(-H <= z-z0) & (z-z0 <= -h)] = ρ0*(1+Δ)
ρ+=(z-z0)/5000.

S = S0*np.ones_like(z)

α = gsw.alpha(S0, T0, p)
T = 4.-(ρ-ρ0)/ρ0/α + np.random.normal(0., 0., size=z.size)

eps, N2, diag = mx.overturn.eps_overturn(z, T, S, 0, 0, return_diagnostics=True, use_ip=False)

plt.plot(diag['dens'], z, label="diag ρ")
plt.plot(diag['dens_sorted'], z, label="sorted diag ρ")
plt.plot(-N2*z/(-9.81/ρ0) + ρ0-7.15, z, label=r"$N^{2}z + Δρ$")
plt.legend()
```

**Comment by gunnarvoet** [comment]
I agree that it would be good to allow for density as input.

For your specific problem, you could use the `overturns_from_CT` option. However, as far as I can see, you'd still need to provide salinity values even though they are not used in that case.
