### ISSUE TITLE
matplotlib not a dev requirement?

### ISSUE THREAD

**Issue by jessecusack** [modscripps/mixsea#8]
Following the contribution tutorial suggests that after running:
`conda env create -f environment.yml`
`conda activate mixsea`

It should then be possible to build the documentation with:
`make docs`

However doing so leads to the following error:
`ModuleNotFoundError: No module named 'matplotlib'`

To fix this either matplotlib needs to be added as a requirement in `environment.yml` or `requirements_dev.txt`

**Comment by gunnarvoet** [comment]
It's a little bit of a mess as pip and conda are being thrown together here. I think you can add it to either.

**Comment by jessecusack** [comment]
I guess we should only use pip if the package is not on conda?

**Comment by gunnarvoet** [comment]
I like to have my environments in conda and having the `environment.yml` makes it easy to set this up. We could have this blank though and only let it include the pip requirements.

Note that `requirements.txt` actually has matplotlib as readthedocs needs it for building the docs... How about including both `requirements.txt` and `requirements_dev.txt` in the conda file?

**Comment by gunnarvoet** [comment]
I'll go ahead and refactor this. In the meantime, you can just install matplotlib into your environment to get going...

**Comment by jessecusack** [comment]
> Note that `requirements.txt` actually has matplotlib as readthedocs needs it for building the docs

Ah I thought that `requirements.txt` was for `pip install`, I didn't realise it was also a requirement for readthedocs.

**Comment by gunnarvoet** [comment]
I think it is even more complicated than that - as far as I understand pip infers the requirements from `setup.py`. We'll learn as we go!
