### ISSUE TITLE
Convention for proportionality constants?

### ISSUE THREAD

**Issue by hdrake** [modscripps/mixsea#90]
I noticed that the `alpha` parameter used in the definition of overturns is actually the inverse of the alpha used by Thorpe 1977 (see his equation 4). Since these constants tend to be approximately unity it doesn't make a *huge* difference but the final dissipation estimates would be off by 20% if someone thought they were setting Thorpe's alpha to 0.95 but actually setting it to 1/0.95.

```python
diag["eps"][isgood] = (
    alpha ** 2 * diag["Lt"][isgood] ** 2 * diag["N2"][isgood] ** 1.5
)
```

I don't know if this is on purpose or perhaps reference to a formula in another paper, but I would either recommend changing the convention to be consistent with Thorpe 1977 or else adding a reference to the paper with this form (and perhaps where the default value of 0.95 comes from).

**Comment by gunnarvoet** [comment]
I think there is a bit of confusion as the proportionality constant has different names in the literature. alpha**2 here would be the C_0 in Thorpe 1977 (equation 6). Dillon (1982) and Ferron (1998) have Lo=a
Lt, thus equating the proportionality constant with the ratio of Ozmidov scale over Thorpe scale. I think this is the usual convention. It may be good to point out that alpha is C0 in Thorpe 1977.

**Comment by hdrake** [comment]
Addressed this in https://github.com/modscripps/mixsea/pull/91
