### ISSUE TITLE
Publish v0.1.1 to pip

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/mixsea#96]
I think we should publish all the additions we made last fall to pip - what do you think, @jessecusack @hdrake ? Unless you think there is anything we should fix before then, I would offer to publish a new release. Then we could also have the documentation point to v0.1.1 (#66) so everyone can benefit from the great additions to the docs.

**Comment by jessecusack** [comment]
Agreed, a version 0.1.1 would be a good next step. I'll try and find some time in the next month to clear up the remaining issues for 0.1.2 :)

**Comment by gunnarvoet** [comment]
Okay, I will get this out to pip when I have a moment. Should we set up a milestone for a 0.1.2 version to collect the issues that we think are most pressing? Or maybe work towards a 0.2 version and leave 0.1.2 open in case we find any bugs to fix until then?

**Comment by hdrake** [comment]
I agree a 0.1.1 release makes sense! I had some ideas for what I'd like to see in v0.1.2 and v0.2.0 in this comment: https://github.com/modscripps/mixsea/issues/60#issuecomment-950923051

Unfortunately I don't have much time to contribute right now, but hopefully will have time to circle back in the coming months.

**Comment by gunnarvoet** [comment]
Thanks @hdrake and no worries about being short on time at the moment, I just mentioned you to acknowledge how much effort you put into this last year =)

I will start a 0.2.0 milestone where we can add #60 and whatever else we think would be good in there. This leaves 0.1.2 open for any fixes with more immediate needs.

**Comment by jessecusack** [comment]
Yes, lets collect together issues into milestones. I'll work through the ones related to Thorpe scales.

If fixing the most pressing issues leads to some breaking changes (e.g. #60), I would vote for the milestone being 0.2.0

**Comment by hdrake** [comment]
> I'll work through the ones related to Thorpe scales.

Feel free to assign me as a reviewer if you want a second set of eyes on anything.

**Comment by gunnarvoet** [comment]
Yes, I think #60 will be a breaking change and am in favor of 0.2.0
